### ISSUE TITLE
<jqx-grid> coming up blank on v2.0.1

### ISSUE THREAD

**Issue by DrEsteban** [jqwidgets/AspNetCore-Mvc-Tag-Helpers#3]
I cannot get the tag helper for `jqx-grid` working.  The area where the grid is supposed to display is blank.  However, when I try to define the same grid using actual Javascript, everything works fine so I don't believe it's an issue with loading the jqx dependencies or anything.

I've tried to create as simple a repro as possible:

*cshtml:*
```
@{
    var test = new[] { new { queryId = "asdf" } };
}
    <jqx-grid width="850" source="test">
        <jqx-grid-columns>
            <jqx-grid-column datafield="queryId" text="Test"></jqx-grid-column>
        </jqx-grid-columns>
    </jqx-grid>
    <div id="jqxgrid">
    </div>

<script>
    $(document).ready(function () {
            var source =
                {
                    localdata: @Json.Serialize(test),
                    datatype: "array"
                };
            var dataAdapter = new $.jqx.dataAdapter(source);
            $("#jqxgrid").jqxGrid(
                {
                    source: dataAdapter,
                    width: "850px",
                    columns: [
                        { text: 'Test', datafield: 'queryId' }
                    ]
                });

        })
</script>
```

Results in the following:
![image](https://user-images.githubusercontent.com/1495037/36508819-a314a486-1712-11e8-8fc5-222babcde1b9.png)

Notice that the grid defined via the Tag Helper is blank, but the grid defined using standard <div> and JS works fine.  I see no errors on the console indicating that something went wrong, it's just not displaying.

**Comment by bmarkov** [comment]
The Grid cannot be bound to [] this way. Please, take a look at our example about how to bind the Grid tag helper.

**Comment by DrEsteban** [comment]
@bmarkov What do you mean?  The Grid cannot be bound to arrays?  Or the Grid cannot be bound to empty array?  (If you mean the latter, notice that in my code the `test` variable is _not_ an empty array.  It has exactly 1 item.)

I _did_ take a look at your examples, and they are all binding to an injected `IEnumerable` model.  (Should be exactly the same as my `test` variable example above.)  I've tried copying the same approach in your samples, but my result in using the Tag Helper is always a blank grid.  (The top example in my image.)  However, I know it's not anything wrong with the model itself, because your standard JS support (as in my example above), always works just fine.  The blank grid issue only comes up when using the Tag Helper, so it seems to be some issue with the HTML/JS generation inside the Tag Helper?

**Comment by DrEsteban** [comment]
@bmarkov Another odd development...

I made a child class of GridTagHelper so I could debug exactly what was going on.  To my surprise, without changing any behavior at all, my child class caused the grid to display correctly.

*cshtml*:
```
@{
    var test = new[] { new { queryId = "asdf", queryDateTime = DateTime.Now } };
}
<jqx-grid width="850" source="test">
    <jqx-grid-columns>
        <jqx-grid-column datafield="queryId" text="Query Id"></jqx-grid-column>
        <jqx-grid-column datafield="queryDateTime" text="Query Date"></jqx-grid-column>
    </jqx-grid-columns>
</jqx-grid>
<my-jqx-grid width="850" source="test">
    <jqx-grid-columns>
        <jqx-grid-column datafield="queryId" text="Query Id"></jqx-grid-column>
        <jqx-grid-column datafield="queryDateTime" text="Query Date"></jqx-grid-column>
    </jqx-grid-columns>
</my-jqx-grid>
```
*Code*:
```
[HtmlTargetElement("my-jqx-grid")]
[RestrictChildren("jqx-grid-columns", new[] { "jqx-grid-column-groups" })]
public class MyGridTagHelper : GridTagHelper
{
}
```
*Result*:
![image](https://user-images.githubusercontent.com/1495037/36563233-54a341d8-17ce-11e8-8bd5-dac1f6b6f1a5.png)

Notice that my overloaded `<my-jqx-grid>` displays properly, but the default `<jqx-grid>` does not.

It looks like by overriding your default implementation, it causes the generated HTML to look much differently:
*`<jqx-grid>`*:
```
<jqx-grid style="display: block;" class="jqx-widget jqx-element jqx-element-no-border"><div id="jqxWidget2bd0e01d7b63" ...
```
*`<my-jqx-grid>`*:
```
<my-jqx-grid><div id="jqxGridea1279dc_1e85_4392_8979_9ff107845b54" ...
```

Notice that the underlying `<div>` has a much different `id` in my overload vs your original implementation.  Looking at the generated JS, it looks like:
```
var jqxGridd7d9b45b_59f7_4636_983b_b2f0c4a0fb0f= new jqxGrid($('#jqxGridea1279dc_1e85_4392_8979_9ff107845b54') ...
```

Notice how in my overloaded example, a `<div>` with that `id` exists.  But in your original implementation's output, it does *not*.  Is this the root cause of the problem?

**Comment by bmarkov** [comment]
Seeing this code, the problem comes from the fact that the Grid scripts are loaded through jqx-all.js not inidividual script files required for the project. jqx-all.js includes also custom elements and jqx-grid is a custom element, not a tag helper when you load it through that file.
